"""Add structured dose/frequency and document fields to prescriptions

Revision ID: 34d10f6aac06
Revises: a125b3012484
Create Date: 2026-02-06 16:25:12.164765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34d10f6aac06'
down_revision: Union[str, None] = 'a125b3012484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Convert dose and frequency from VARCHAR to JSON with USING clause
    # Wrap existing string values in JSON object for backward compatibility
    op.execute("""
        ALTER TABLE prescription_items
        ALTER COLUMN dose TYPE JSON
        USING CASE
            WHEN dose IS NOT NULL THEN json_build_object('pattern', dose, 'structured', false)
            ELSE NULL
        END
    """)

    op.execute("""
        ALTER TABLE prescription_items
        ALTER COLUMN frequency TYPE JSON
        USING json_build_object('pattern', frequency, 'structured', false)
    """)

    op.add_column('prescriptions', sa.Column('document_s3_key', sa.String(length=512), nullable=True))
    op.add_column('prescriptions', sa.Column('document_file_name', sa.String(length=255), nullable=True))
    op.add_column('prescriptions', sa.Column('document_file_size', sa.Integer(), nullable=True))
    op.add_column('prescriptions', sa.Column('document_mime_type', sa.String(length=128), nullable=True))
    op.add_column('prescriptions', sa.Column('document_uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'prescriptions', ['document_s3_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prescriptions', type_='unique')
    op.drop_column('prescriptions', 'document_uploaded_at')
    op.drop_column('prescriptions', 'document_mime_type')
    op.drop_column('prescriptions', 'document_file_size')
    op.drop_column('prescriptions', 'document_file_name')
    op.drop_column('prescriptions', 'document_s3_key')

    # Convert JSON back to VARCHAR (extract 'pattern' key if it exists)
    op.execute("""
        ALTER TABLE prescription_items
        ALTER COLUMN frequency TYPE VARCHAR(128)
        USING CASE
            WHEN frequency ? 'pattern' THEN frequency->>'pattern'
            ELSE frequency::text
        END
    """)

    op.execute("""
        ALTER TABLE prescription_items
        ALTER COLUMN dose TYPE VARCHAR(64)
        USING CASE
            WHEN dose IS NULL THEN NULL
            WHEN dose ? 'pattern' THEN dose->>'pattern'
            ELSE dose::text
        END
    """)
    # ### end Alembic commands ###
