"""Add column comments and rename medication_id to medication_cis

Revision ID: a125b3012484
Revises: 8a9b0c1d2e3f
Create Date: 2026-02-05 17:41:34.776681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a125b3012484'
down_revision: Union[str, None] = '8a9b0c1d2e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('global_medications', 'cis',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='CIS Code from French BDPM API',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('global_medications', 'element_pharmaceutique',
               existing_type=sa.VARCHAR(length=255),
               comment='Pharmaceutical element / product name',
               existing_nullable=False)
    op.alter_column('global_medications', 'forme_pharmaceutique',
               existing_type=sa.VARCHAR(length=128),
               comment='Pharmaceutical form (tablet, capsule, etc.)',
               existing_nullable=False)
    op.alter_column('global_medications', 'status_autorisation',
               existing_type=sa.VARCHAR(length=128),
               comment='Authorization status (e.g., "Autorisation active")',
               existing_nullable=False)
    op.alter_column('global_medications', 'type_procedure',
               existing_type=sa.VARCHAR(length=128),
               comment='Procedure type (e.g., "Procédure nationale")',
               existing_nullable=False)
    op.alter_column('global_medications', 'etat_commercialisation',
               existing_type=sa.VARCHAR(length=128),
               comment='Commercialization state (e.g., "Commercialisée")',
               existing_nullable=False)
    op.alter_column('global_medications', 'date_amm',
               existing_type=sa.DATE(),
               comment='Marketing Authorization Date',
               existing_nullable=True)
    op.alter_column('global_medications', 'titulaire',
               existing_type=sa.VARCHAR(length=255),
               comment='License holder / manufacturer name',
               existing_nullable=False)
    op.alter_column('global_medications', 'sync_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last successful sync from external API',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('prescription_items', sa.Column('medication_cis', sa.Integer(), nullable=True))
    op.drop_constraint('prescription_items_medication_id_fkey', 'prescription_items', type_='foreignkey')
    op.create_foreign_key(None, 'prescription_items', 'global_medications', ['medication_cis'], ['cis'], ondelete='SET NULL')
    op.drop_column('prescription_items', 'medication_id')
    op.drop_constraint('uq_users_keycloak_subject', 'users', type_='unique')
    op.create_unique_constraint('uq_users_subject_tenant', 'users', ['keycloak_subject', 'tenant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_subject_tenant', 'users', type_='unique')
    op.create_unique_constraint('uq_users_keycloak_subject', 'users', ['keycloak_subject'])
    op.add_column('prescription_items', sa.Column('medication_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'prescription_items', type_='foreignkey')
    op.create_foreign_key('prescription_items_medication_id_fkey', 'prescription_items', 'global_medications', ['medication_id'], ['cis'], ondelete='SET NULL')
    op.drop_column('prescription_items', 'medication_cis')
    op.alter_column('global_medications', 'sync_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last successful sync from external API',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('global_medications', 'titulaire',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='License holder / manufacturer name',
               existing_nullable=False)
    op.alter_column('global_medications', 'date_amm',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Marketing Authorization Date',
               existing_nullable=True)
    op.alter_column('global_medications', 'etat_commercialisation',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Commercialization state (e.g., "Commercialisée")',
               existing_nullable=False)
    op.alter_column('global_medications', 'type_procedure',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Procedure type (e.g., "Procédure nationale")',
               existing_nullable=False)
    op.alter_column('global_medications', 'status_autorisation',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Authorization status (e.g., "Autorisation active")',
               existing_nullable=False)
    op.alter_column('global_medications', 'forme_pharmaceutique',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Pharmaceutical form (tablet, capsule, etc.)',
               existing_nullable=False)
    op.alter_column('global_medications', 'element_pharmaceutique',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Pharmaceutical element / product name',
               existing_nullable=False)
    op.alter_column('global_medications', 'cis',
               existing_type=sa.INTEGER(),
               comment='CIS Code from French BDPM API',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
